#FROM rust:1.60.0
#WORKDIR /rust/src
#ENV PATH="/rust/bin:${PATH}"
#RUN apt-get update && \
#apt-get install build-essential protobuf-compiler librdkafka-dev -y 
#COPY . .
#RUN cargo install --path .
#ENTRYPOINT ["./rust-codepix"]